# Generated by Django 5.2.1 on 2025-05-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Upload a representative thumbnail (e.g., 600×400 px).', null=True, upload_to='projects/')),
                ('live_link', models.URLField(blank=True, help_text='Optional: link to live demo or repo')),
                ('github_link', models.URLField(blank=True, help_text='Optional: GitHub repo URL')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g. Django, JavaScript, Python)', max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
