# Generated by Django 5.2.1 on 2025-05-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.CharField(help_text='Short summary for listing', max_length=300)),
                ('content', models.TextField(help_text='Full content (HTML or Markdown)')),
                ('featured_image', models.ImageField(blank=True, help_text='Optional: featured image (e.g., 800×600 px)', null=True, upload_to='blog/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g. Django, Python, Tutorial)', max_length=200)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
